### ISSUE TITLE
Support .ico format

### ISSUE THREAD

**Issue by trung** [devgg/fonticon#7]
It'd be good to have .ico format download

**Comment by victor-lund** [comment]
Came here to say this. Please add .ico format!

**Comment by devgg** [comment]
I did some digging and there does not seem to be a simple way to enable this. Since there is no backend it would need to be done completely in Javascript and so far I could only find a few hacks that will not work on all browsers. So for the time being I would suggest using a converter such as [icoconverter.com](https://www.icoconverter.com/).

**Comment by devgg** [comment]
Thank you guys for reporting but at this point there does not seem to be a satisfying fix.

**Comment by devgg** [comment]
I spent some time today and wrote a backend just for .ico creation ;-).
